In [25]:
import pandas as pd

df = pd.read_csv("../data/raw/relatorios.csv")
df.head()

,ID COMPLETO DO PEDIDO,NOME DA LOJA,ID DA LOJA,DATA E HORA DO PEDIDO,TURNO,ID CURTO DO PEDIDO,STATUS FINAL DO PEDIDO,VALOR DOS ITENS (R$),TOTAL PAGO PELO CLIENTE (R$),TAXA DE ENTREGA PAGA PELO CLIENTE (R$),...,INCENTIVO PROMOCIONAL DA LOJA (R$),INCENTIVO PROMOCIONAL DA REDE (R$),TAXA DE SERVIÇO (R$),TAXAS E COMISSOES (R$),VALOR LIQUIDO (R$),FORMA DE PAGAMENTO,TIPO DE ENTREGA,PRODUTO LOGISTICO,CANAL DE VENDA,arquivo_origem
0,f4baa630-683a-47b3-9b46-38c7ddb821ac,Thaís Alves Confeitaria e Doceria,1087647,26/04/2026 15:21:45,CAFÉ DA TARDE,9349,CONCLUIDO,32.6,26.43,0.99,...,5.0,0,0.99,-7.23,20.37,Pgto via APP - Carteira Digital (Visa),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
1,648904d6-1e94-4cd7-9429-55eb132164a0,Thaís Alves Confeitaria e Doceria,1087647,25/04/2026 17:20:49,JANTAR,2452,CONCLUIDO,18.9,13.88,0.99,...,5.0,0,0.99,-3.64,10.26,Pgto via APP - Crédito (Mastercard),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
2,9662e3b2-ac98-4526-a27e-34563f02c78d,Thaís Alves Confeitaria e Doceria,1087647,25/04/2026 16:41:14,CAFÉ DA TARDE,9384,CONCLUIDO,18.9,19.89,0.00,...,0.0,0,0.99,-4.95,13.95,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
3,04921db6-ced8-49da-9a85-801611f4c3b4,Thaís Alves Confeitaria e Doceria,1087647,22/04/2026 14:31:03,ALMOÇO,2628,CONCLUIDO,42.9,33.17,0.00,...,5.0,0,0.99,-9.93,27.97,Pgto via APP - Crédito (Mastercard),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
4,8a478648-2651-4557-9b2a-0ee92811ce14,Thaís Alves Confeitaria e Doceria,1087647,21/04/2026 16:48:21,CAFÉ DA TARDE,742,CONCLUIDO,18.9,19.89,8.99,...,5.0,0,0.99,-4.95,8.95,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...

In [26]:
filtro = ~(df['PRODUTO LOGISTICO'] == "ENTREGA PARCEIRA IFOOD")
df[filtro]

,ID COMPLETO DO PEDIDO,NOME DA LOJA,ID DA LOJA,DATA E HORA DO PEDIDO,TURNO,ID CURTO DO PEDIDO,STATUS FINAL DO PEDIDO,VALOR DOS ITENS (R$),TOTAL PAGO PELO CLIENTE (R$),TAXA DE ENTREGA PAGA PELO CLIENTE (R$),...,INCENTIVO PROMOCIONAL DA LOJA (R$),INCENTIVO PROMOCIONAL DA REDE (R$),TAXA DE SERVIÇO (R$),TAXAS E COMISSOES (R$),VALOR LIQUIDO (R$),FORMA DE PAGAMENTO,TIPO DE ENTREGA,PRODUTO LOGISTICO,CANAL DE VENDA,arquivo_origem
96,55ebf8ff-08ee-4b38-a5c7-52030f0b392c,Thaís Alves Confeitaria e Doceria,1087647,14/02/2026 21:05:39,JANTAR,8408,CANCELADO,37.8,27.45,0.0,...,4.99,0,0.99,0.0,0.0,Pgto via APP - Crédito (Mastercard),PARA RETIRAR,NaN,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...

In [27]:
filtro_status = df["STATUS FINAL DO PEDIDO"] == "CONCLUIDO"
df = df[filtro_status]
df

,ID COMPLETO DO PEDIDO,NOME DA LOJA,ID DA LOJA,DATA E HORA DO PEDIDO,TURNO,ID CURTO DO PEDIDO,STATUS FINAL DO PEDIDO,VALOR DOS ITENS (R$),TOTAL PAGO PELO CLIENTE (R$),TAXA DE ENTREGA PAGA PELO CLIENTE (R$),...,INCENTIVO PROMOCIONAL DA LOJA (R$),INCENTIVO PROMOCIONAL DA REDE (R$),TAXA DE SERVIÇO (R$),TAXAS E COMISSOES (R$),VALOR LIQUIDO (R$),FORMA DE PAGAMENTO,TIPO DE ENTREGA,PRODUTO LOGISTICO,CANAL DE VENDA,arquivo_origem
0,f4baa630-683a-47b3-9b46-38c7ddb821ac,Thaís Alves Confeitaria e Doceria,1087647,26/04/2026 15:21:45,CAFÉ DA TARDE,9349,CONCLUIDO,32.60,26.43,0.99,...,5.0,0,0.99,-7.23,20.37,Pgto via APP - Carteira Digital (Visa),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
1,648904d6-1e94-4cd7-9429-55eb132164a0,Thaís Alves Confeitaria e Doceria,1087647,25/04/2026 17:20:49,JANTAR,2452,CONCLUIDO,18.90,13.88,0.99,...,5.0,0,0.99,-3.64,10.26,Pgto via APP - Crédito (Mastercard),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
2,9662e3b2-ac98-4526-a27e-34563f02c78d,Thaís Alves Confeitaria e Doceria,1087647,25/04/2026 16:41:14,CAFÉ DA TARDE,9384,CONCLUIDO,18.90,19.89,0.00,...,0.0,0,0.99,-4.95,13.95,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
3,04921db6-ced8-49da-9a85-801611f4c3b4,Thaís Alves Confeitaria e Doceria,1087647,22/04/2026 14:31:03,ALMOÇO,2628,CONCLUIDO,42.90,33.17,0.00,...,5.0,0,0.99,-9.93,27.97,Pgto via APP - Crédito (Mastercard),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
4,8a478648-2651-4557-9b2a-0ee92811ce14,Thaís Alves Confeitaria e Doceria,1087647,21/04/2026 16:48:21,CAFÉ DA TARDE,742,CONCLUIDO,18.90,19.89,8.99,...,5.0,0,0.99,-4.95,8.95,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,d35b3048-27ec-4dc6-9daa-81a46c662bea,Thaís Alves Confeitaria e Doceria,1087647,11/02/2026 15:35:32,CAFÉ DA TARDE,4474,CONCLUIDO,51.80,50.78,12.99,...,5.0,0,0.99,-12.26,34.54,Pgto via APP - Crédito (Visa),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...
99,9a2cb5a5-0611-46c0-8983-28fc5b47ecb8,Thaís Alves Confeitaria e Doceria,1087647,08/02/2026 16:35:21,CAFÉ DA TARDE,8864,CONCLUIDO,32.90,20.89,9.99,...,5.0,0,0.99,-7.31,20.59,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...
100,0cbe3840-cbf6-4d8c-bdfb-524684f90036,Thaís Alves Confeitaria e Doceria,1087647,08/02/2026 13:38:26,ALMOÇO,7371,CONCLUIDO,18.90,19.89,0.00,...,0.0,0,0.99,-4.95,13.95,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...
101,fe36e72a-adbf-4e99-b7bb-900aaec82b30,Thaís Alves Confeitaria e Doceria,1087647,03/02/2026 16:38:03,CAFÉ DA TARDE,378,CONCLUIDO,34.99,27.23,0.00,...,0.0,0,0.99,-9.17,25.82,Pgto via APP - Crédito (Visa),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...
102,a9e26868-f2bd-46bc-bec0-263d85a1aa9d,Thaís Alves Confeitaria e Doceria,1087647,01/02/2026 15:45:11,CAFÉ DA TARDE,1156,CONCLUIDO,34.99,34.22,6.99,...,0.0,0,0.99,-9.17,25.82,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...

In [29]:
df["DATA E HORA DO PEDIDO"] = pd.to_datetime(df["DATA E HORA DO PEDIDO"], dayfirst=True)
df["DATA PEDIDO"] = df["DATA E HORA DO PEDIDO"].dt.date
df["HORA PEDIDO"] = df['DATA E HORA DO PEDIDO'].dt.time
df

,ID COMPLETO DO PEDIDO,NOME DA LOJA,ID DA LOJA,DATA E HORA DO PEDIDO,TURNO,ID CURTO DO PEDIDO,STATUS FINAL DO PEDIDO,VALOR DOS ITENS (R$),TOTAL PAGO PELO CLIENTE (R$),TAXA DE ENTREGA PAGA PELO CLIENTE (R$),...,TAXA DE SERVIÇO (R$),TAXAS E COMISSOES (R$),VALOR LIQUIDO (R$),FORMA DE PAGAMENTO,TIPO DE ENTREGA,PRODUTO LOGISTICO,CANAL DE VENDA,arquivo_origem,DATA PEDIDO,HORA PEDIDO
0,f4baa630-683a-47b3-9b46-38c7ddb821ac,Thaís Alves Confeitaria e Doceria,1087647,2026-04-26 15:21:45,CAFÉ DA TARDE,9349,CONCLUIDO,32.60,26.43,0.99,...,0.99,-7.23,20.37,Pgto via APP - Carteira Digital (Visa),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...,2026-04-26,15:21:45
1,648904d6-1e94-4cd7-9429-55eb132164a0,Thaís Alves Confeitaria e Doceria,1087647,2026-04-25 17:20:49,JANTAR,2452,CONCLUIDO,18.90,13.88,0.99,...,0.99,-3.64,10.26,Pgto via APP - Crédito (Mastercard),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...,2026-04-25,17:20:49
2,9662e3b2-ac98-4526-a27e-34563f02c78d,Thaís Alves Confeitaria e Doceria,1087647,2026-04-25 16:41:14,CAFÉ DA TARDE,9384,CONCLUIDO,18.90,19.89,0.00,...,0.99,-4.95,13.95,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...,2026-04-25,16:41:14
3,04921db6-ced8-49da-9a85-801611f4c3b4,Thaís Alves Confeitaria e Doceria,1087647,2026-04-22 14:31:03,ALMOÇO,2628,CONCLUIDO,42.90,33.17,0.00,...,0.99,-9.93,27.97,Pgto via APP - Crédito (Mastercard),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...,2026-04-22,14:31:03
4,8a478648-2651-4557-9b2a-0ee92811ce14,Thaís Alves Confeitaria e Doceria,1087647,2026-04-21 16:48:21,CAFÉ DA TARDE,742,CONCLUIDO,18.90,19.89,8.99,...,0.99,-4.95,8.95,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_0c5c534d9eb3f7dd973f4e00d59c...,2026-04-21,16:48:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,d35b3048-27ec-4dc6-9daa-81a46c662bea,Thaís Alves Confeitaria e Doceria,1087647,2026-02-11 15:35:32,CAFÉ DA TARDE,4474,CONCLUIDO,51.80,50.78,12.99,...,0.99,-12.26,34.54,Pgto via APP - Crédito (Visa),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...,2026-02-11,15:35:32
99,9a2cb5a5-0611-46c0-8983-28fc5b47ecb8,Thaís Alves Confeitaria e Doceria,1087647,2026-02-08 16:35:21,CAFÉ DA TARDE,8864,CONCLUIDO,32.90,20.89,9.99,...,0.99,-7.31,20.59,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...,2026-02-08,16:35:21
100,0cbe3840-cbf6-4d8c-bdfb-524684f90036,Thaís Alves Confeitaria e Doceria,1087647,2026-02-08 13:38:26,ALMOÇO,7371,CONCLUIDO,18.90,19.89,0.00,...,0.99,-4.95,13.95,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...,2026-02-08,13:38:26
101,fe36e72a-adbf-4e99-b7bb-900aaec82b30,Thaís Alves Confeitaria e Doceria,1087647,2026-02-03 16:38:03,CAFÉ DA TARDE,378,CONCLUIDO,34.99,27.23,0.00,...,0.99,-9.17,25.82,Pgto via APP - Crédito (Visa),ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...,2026-02-03,16:38:03
102,a9e26868-f2bd-46bc-bec0-263d85a1aa9d,Thaís Alves Confeitaria e Doceria,1087647,2026-02-01 15:45:11,CAFÉ DA TARDE,1156,CONCLUIDO,34.99,34.22,6.99,...,0.99,-9.17,25.82,Pgto via APP - PIX,ENTREGA,ENTREGA PARCEIRA IFOOD,iFood,relatorio-pedidos_c58bdf057fa128563632d93e0e4f...,2026-02-01,15:45:11

In [30]:
df.dtypes

ID COMPLETO DO PEDIDO                                str
NOME DA LOJA                                         str
ID DA LOJA                                         int64
DATA E HORA DO PEDIDO                     datetime64[us]
TURNO                                                str
ID CURTO DO PEDIDO                                 int64
STATUS FINAL DO PEDIDO                               str
VALOR DOS ITENS (R$)                             float64
TOTAL PAGO PELO CLIENTE (R$)                     float64
TAXA DE ENTREGA PAGA PELO CLIENTE (R$)           float64
INCENTIVO PROMOCIONAL DO IFOOD (R$)              float64
INCENTIVO PROMOCIONAL DA LOJA (R$)               float64
INCENTIVO PROMOCIONAL DA REDE (R$)                 int64
TAXA DE SERVIÇO (R$)                             float64
TAXAS E COMISSOES (R$)                           float64
VALOR LIQUIDO (R$)                               float64
FORMA DE PAGAMENTO                                   str
TIPO DE ENTREGA                                      str
PRODUTO LOGISTICO                                    str
CANAL DE VENDA                                       str
arquivo_origem                                       str
DATA PEDIDO                                       object
HORA PEDIDO                                       object
dtype: object